export const enum Areas {
    LUXERION,
    YUSNAAN,
    DEAD_DUNES,
    WILDLANDS,
    GLOBAL,
    ULTIMATE_LAIR,
    ARK
}

export const enum MainQuests {
    NOEL = 1,
    SNOW = 2,
    CAIUS = 3,
    FANG = 4,
    SAZH = 5,
}

export const enum Days {
    PROLOGUE,
    ONE,
    TWO,
    THREE,
    FOUR,
    FIVE,
    SIX,
    SEVEN,
    EIGHT,
    NINE,
    TEN,
    ELEVEN,
    TWELVE,
    THIRTEEEN,
    FINAL
}

export const enum EPAbilities {
    OVERCLOCK,
    CURAGA,
    ARISE,
    ESUNADA,
    DECOY,
    QUAKE,
    ARMY_OF_ONE,
    ESCAPE,
    CHRONOSTASIS,
    TELEPORT
}

export const enum Bosses {
    ZALTYS_PROLOGUE,
    NOEL,
    SNOW,
    CAIUS,
    GRENDEL,
    ERESHKIGAL,
    BHUNIVELZE,
    AERONITE
}

export const enum MiniBosses {
    CHOCOBO_EATER,
    CYCLOPS,
    CACTAIR
}

type TimeMinutes = '00' | '15' | '30' | '45';
type D3 = '0' | '1' | '2' | '3';
type D9 = D3  | '4' | '5' | '6' | '7' | '8' | '9';
type TimeHours = `0${D9}` | `1${D9}` | `2${D3}`;

export type Time = `${TimeHours}:${TimeMinutes}`;

const locations = [
    "Gorgonopsid Omega Drop",
    "Zaltys Omega Drop",
    "Miniflan Omega Drop",
    "Hanuman Omega Drop",
    "Zomok Omega Drop",
    "Snow Drop",
    "Grendel/Parandus Drop",
    "Goblin Omega Drop",
    "Gremlin Omega Drop",
    "Niblet Omega Drop",
    "Goblot Omega Drop",
    "Triffid Omega Drop",
    "Schrodinger Omega Drop",
    "Earth Eater Omega Drop",
    "Chocobo Eater Omega Drop",
    "Desert Sahagin Omega Drop",
    "Sugriva Omega Drop",
    "Chimera Omega Drop",
    "Rafflesia Omega Drop",
    "Cactuar Omega Drop",
    "Aeronite Drop",
    "Ereshkigal Drop",
    "Gurangatch Omega Drop",
    "Skata'ne Omega Drop",
    "Dryad Omega Drop",
    "Dreadnought Omega Drop",
    "Hoplite Omega Drop",
    "Aster Protoflorian Omega Drop",
    "Gaunt Omega Drop",
    "Arcangeli Omega Drop",
    "Ectopudding Omega Drop",
    "Meonekton Omega Drop",
    "Luxerion Cathedral Proof of Courage",
    "Luxerion Pilgrim's Passage Violet Amulet",
    "Yusnaan Reveler's Quarter Lapis Lazuli",
    "Yusnaan Industrial Area Power Booster",
    "Wildlands Moogle Village Moogle Dust",
    "Wildlands Research Camp Photo Frame",
    "Wildlands Poltae Etro's Forbidden Tome",
    "Wildlands North Broken Gyroscope",
    "Dead Dunes Temple Ruins Golden Scarab",
    "Dead Dunes Oasis Lighthouse Key to the Sand Gate",
    "Wildlands South of Aryas Village Key to the Green Gate",
    "Dead Dunes Shrine at Grave of the Colossi Bandit's Bloodseal",
    "Yusnaan Tunnel Oath of the Merchants Guild",
    "Yusnaan Industrial Area Jade Hair Comb",
    "Yusnaan Industrial Area Bronze Pocket Watch",
    "Dead Dunes Temple Ruins Golden Chamber Lower",
    "Dead Dunes Giant's Sandbox",
    "Dead Dunes Giant's Sandbox",
    "Dead Dunes Giant's Sandbox",
    "Dead Dunes Ruffian Cliff",
    "Dead Dunes Dry Floodlands",
    "Dead Dunes Oasis Lighthouse",
    "Dead Dunes Oasis Lighthouse",
    "Dead Dunes Atomos's Sand",
    "Dead Dunes Grave of the Colossi",
    "Dead Dunes Grave of the Colossi",
    "Dead Dunes Grave of the Colossi",
    "Dead Dunes Atomos's Sand",
    "Dead Dunes Ruffian 2nd Floor",
    "Dead Dunes Temple Ruins Chamber of Dusk Upper",
    "Dead Dunes Temple Ruins Chamber of Plenilune Upper",
    "Dead Dunes Temple Ruins Chamber of Plenilune Upper",
    "Dead Dunes Temple Ruins Chamber of Plenilune Upper",
    "Dead Dunes Temple Ruins Chamber of Plenilune Lower",
    "Dead Dunes Temple Ruins Chamber of Plenilune Lower",
    "Dead Dunes Temple Ruins Chamber of Plenilune Lower",
    "Dead Dunes Temple Ruins Sacred Grove",
    "Dead Dunes Temple Ruins Golden Chamber Upper",
    "Dead Dunes Shrine at Dry Floodlands",
    "Dead Dunes Temple Ruins Golden Chamber Lower",
    "Dead Dunes Temple Ruins Golden Chamber Lower",
    "Dead Dunes Temple Ruins Golden Chamber Lower",
    "Dead Dunes Temple Ruins Scorched Earth Lower",
    "Dead Dunes Temple Ruins Scorched Earth Upper",
    "Dead Dunes Temple Ruins Scorched Earth Upper",
    "Dead Dunes Temple Ruins Golden Chamber Upper",
    "Dead Dunes Shrine at Atomos's Sands",
    "Dead Dunes Giant's Sandbox",
    "Dead Dunes Dry Floodlands",
    "Ultimate Lair",
    "Ultimate Lair",
    "Ultimate Lair",
    "Ultimate Lair",
    "Luxerion North Station Plaza Ladder",
    "Luxerion The Avenue Ladder",
    "Luxerion Gallery Steps",
    "Luxerion 2nd Ave",
    "Luxerion Pilgrim's Passage Grass Area",
    "Luxerion Old Theater Platform",
    "Luxerion Forsaken Graveyard",
    "Luxerion South Station",
    "Luxerion Warehouse District",
    "Luxerion Residences",
    "Luxerion Forsaken Graveyard",
    "Luxerion Den of Shadows",
    "Luxerion Near Phone",
    "Luxerion Den of Shadows",
    "Luxerion Near Phone",
    "Luxerion Near Phone",
    "Luxerion Marketplace",
    "Luxerion Forsaken Graveyard",
    "Final Day Altar of Salvation",
    "Final Day Altar of Judgment",
    "Final Day Altar of Atonement",
    "Final Day Altar of Birth",
    "Final Day Temple of Light",
    "Final Day Temple of Light",
    "Final Day Temple of Light",
    "Ark Day 1",
    "Ark Day 1",
    "Ark Day 1",
    "Ark Day 1",
    "Ark Day 1",
    "Ark Day 2",
    "Ark Day 2",
    "Ark Day 2",
    "Ark Day 3",
    "Ark Day 4",
    "Ark Day 4",
    "Ark Day 5",
    "Ark Day 6",
    "Ark Day 7",
    "Ark Day 8",
    "Ark Day 9",
    "Ark Day 10",
    "Ark Day 11",
    "Ark Day 12",
    "Ark Day 13",
    "Ark Day 13",
    "Ark Day 13",
    "Ark Day 14",
    "Wildlands Jagd Woods",
    "Wildlands Grasslands",
    "Wildlands Poltae",
    "Wildlands Canopus Farms",
    "Wildlands Rocky Crag",
    "Wildlands Grasslands",
    "Wildlands Aryas Village",
    "Wildlands Grasslands",
    "Wildlands Eremite Plains",
    "Wildlands Eremite Plains",
    "Wildlands Moogle Village",
    "Wildlands City of Ruins",
    "Wildlands Rocky Crag",
    "Wildlands Rocky Crag",
    "Wildlands Aryas Village",
    "Wildlands Poltae",
    "Wildlands Crash Site Fragment",
    "Wildlands Goddess Temple",
    "Wildlands Goddess Temple",
    "Wildlands Goddess Temple",
    "Wildlands Goddess Temple",
    "Wildlands Goddess Temple",
    "Wildlands Goddess Temple",
    "Wildlands Goddess Temple",
    "Wildlands Goddess Temple",
    "Wildlands Goddess Temple",
    "Yusnaan Glutton's Quarter",
    "Yusnaan Aromatic Market",
    "Yusnaan Central Ave",
    "Yusnaan Coliseum Square",
    "Yusnaan Warehouse District ID Card",
    "Yusnaan Coliseum Square Musical",
    "Yusnaan East from Cactuar Statue Musical",
    "Yusnaan West of Station Musical",
    "Yusnaan Near Cactuar Statue",
    "Yusnaan Reveler's Quarter",
    "Yusnaan Augur's Quarter",
    "Yusnaan Patron's Palace",
    "Yusnaan Hawker's Row",
    "Yusnaan Augur's Quarter",
    "Yusnaan Warehouse District",
    "Yusnaan Augur's Quarter",
    "Yusnaan Supply Line",
    "Yusnaan Industrial Area",
    "Yusnaan Lower City",
    "Yusnaan Glutton's Quarter",
    "Yusnaan Reveler's Quarter",
    "Yusnaan Patron's Palace",
    "Yusnaan Patron's Palace",
    "Yusnaan Patron's Palace",
    "Yusnaan Patron's Palace",
    "Yusnaan Slaughterhouse",
    "Yusnaan Slaughterhouse",
    "Yusnaan Slaughterhouse",
    "Yusnaan Slaughterhouse",
    "Yusnaan Slaughterhouse",
    "Yusnaan Slaughterhouse",
    "Yusnaan Slaughterhouse",
    "Yusnaan Slaughterhouse",
    "Yusnaan Slaughterhouse",
    "Yusnaan Slaughterhouse",
    "Yusnaan Slaughterhouse - Fighting Actress",
    "Yusnaan Slaughterhouse - Fighting Actress",
    "Yusnaan Slaughterhouse - Fighting Actress",
    "Yusnaan Slaughterhouse - Tanbam's Taboo",
    "Dead Dunes Temple Ruins Sacred Grove Bhakti",
    "Dead Dunes Unappraised 1",
    "Dead Dunes Unappraised 5",
    "Dead Dunes Unappraised 10",
    "Dead Dunes Unappraised 20",
    "Dead Dunes Unappraised 50",
    "Dead Dunes Pilgrim's Crux",
    "Dead Dunes Pilgrim's Crux",
    "Dead Dunes Pilgrim's Crux",
    "Dead Dunes Pilgrim's Crux",
    "Dead Dunes Pilgrim's Crux",
    "Dead Dunes Pilgrim's Crux",
    "Dead Dunes Pilgrim's Crux",
    "Dead Dunes Pilgrim's Crux",
    "Dead Dunes Pilgrim's Crux",
    "Dead Dunes Pilgrim's Crux",
    "Dead Dunes Pilgrim's Crux",
    "Dead Dunes Pilgrim's Crux",
    "Dead Dunes Pilgrim's Crux",
    "Dead Dunes Pilgrim's Crux",
    "Luxerion 1st Ave Rubber Ball",
    "Luxerion Warehouse District Thunderclap Cap",
    "Luxerion Marketplace Pen",
    "Quest Born from chaos",
    "Dead Dunes Loupe",
    "Wildlands Aryas Village Beloved's Gift",
    "Quest The things she lost",
    "Quest The things she lost",
    "Quest Where are you, Holmes?",
    "Quest Where are you, Holmes?",
    "Quest Where are you, Holmes?",
    "Quest Like clockwork",
    "Quest Like clockwork",
    "Quest Dying wish",
    "Quest Dying wish",
    "Quest Suspicious supply device",
    "Quest Suspicious supply device",
    "Quest Born from chaos",
    "Quest Born from chaos",
    "Quest Soul Seeds",
    "Quest Soul Seeds",
    "Quest Faster than Lightning",
    "Quest Faster than Lightning",
    "Quest Treasured ball",
    "Quest Treasured ball",
    "Quest The angel's tears",
    "Quest The angel's tears",
    "Quest The saint's stone",
    "Quest The saint's stone",
    "Quest The saint's stone",
    "Quest Whither faith",
    "Quest Whither faith",
    "Quest The avid reader",
    "Quest The avid reader",
    "Quest Buried passion",
    "Quest Buried passion",
    "Quest The girl who cried wolf",
    "Quest The girl who cried wolf",
    "Quest Stuck in a gem",
    "Quest Stuck in a gem",
    "Quest Get the girl",
    "Quest Get the girl",
    "Quest A rose by any other name",
    "Quest A rose by any other name",
    "Quest A rose by any other name",
    "Quest A rose by any other name",
    "Quest Voices from the grave",
    "Quest Voices from the grave",
    "Quest A father's request",
    "Quest A father's request",
    "Quest The hunter's challenge",
    "Quest The hunter's challenge",
    "Quest The hunter's challenge",
    "Quest A final cure",
    "Quest A final cure",
    "Quest A final cure",
    "Quest Fuzzy search",
    "Quest Fuzzy search",
    "Quest Fuzzy search",
    "Quest Round 'em up",
    "Quest Round 'em up",
    "Quest Chocobo cheer",
    "Quest Chocobo cheer",
    "Quest Chocobo cheer",
    "Quest Peace and quiet, kupo",
    "Quest Peace and quiet, kupo",
    "Quest Peace and quiet, kupo",
    "Quest Saving an angel",
    "Quest Saving an angel",
    "Quest Omega point",
    "Quest Omega point",
    "Quest The old man and the field",
    "Quest The old man and the field",
    "Quest Land of our forebears",
    "Quest Land of our forebears",
    "Quest A taste of the past",
    "Quest A taste of the past",
    "Quest A taste of the past",
    "Quest Dog, doctor and assistant",
    "Quest Dog, doctor and assistant",
    "Main Quest 5",
    "Main Quest 5",
    "Main Quest 5",
    "Quest The right stuff",
    "Quest The right stuff",
    "Quest The secret lives of sheep",
    "Quest The secret lives of sheep",
    "Quest Where are you, Moogle?",
    "Quest Where are you, Moogle?",
    "Quest Where are you, Moogle?",
    "Quest Mercy of a goddess",
    "Quest Mercy of a goddess",
    "Quest The grail of Valhalla",
    "Quest The grail of Valhalla",
    "Quest The grail of Valhalla",
    "Quest To live in chaos",
    "Quest To live in chaos",
    "Quest To live in chaos",
    "Quest The life of a machine",
    "Quest Old rivals",
    "Quest Old rivals",
    "Quest His wife's dream",
    "Quest His wife's dream",
    "Quest Tool of the trade",
    "Quest Tool of the trade",
    "Quest Adonis's audition",
    "Quest Adonis's audition",
    "Quest What rough beast slouches",
    "Quest What rough beast slouches",
    "Quest Skeletons in the closet",
    "Quest Skeletons in the closet",
    "Quest Last One standing",
    "Quest Last One standing",
    "Quest Last One standing",
    "Quest Fireworks in a bottle",
    "Quest Fireworks in a bottle",
    "Quest The fighting actress",
    "Quest The fighting actress",
    "Quest Songless diva",
    "Quest Songless diva",
    "Quest Stolen things",
    "Quest Stolen things",
    "Quest Fireworks for a steal",
    "Quest Fireworks for a steal",
    "Quest A testing proposition",
    "Quest A testing proposition",
    "Quest Last date",
    "Quest Last date",
    "Quest Free will",
    "Quest Free will",
    "Quest Free will",
    "Quest Friends forever",
    "Quest Friends forever",
    "Quest Friends forever",
    "Quest Family food",
    "Quest Family food",
    "Quest Tanbam's taboo",
    "Quest Tanbam's taboo",
    "Quest Play it for me",
    "Quest Play it for me",
    "Quest Adoring adornments",
    "Quest Adoring adornments",
    "Quest Adoring Candice",
    "Quest Adoring Candice",
    "Quest Adoring Candice",
    "Quest Death safari",
    "Quest Death safari",
    "Quest Death safari",
    "Quest Death safari",
    "Quest Death safari",
    "Quest Death game",
    "Quest Death game",
    "Quest Death game",
    "Quest Killing time",
    "Quest Killing time",
    "Quest Matchmaker",
    "Quest Matchmaker",
    "Quest Mother and daughter",
    "Quest Mother and daughter",
    "Quest To save the sinless",
    "Quest To save the sinless",
    "Ereshkigal",
    "Quest Revenge is sweet",
    "Quest Revenge is sweet",
    "Quest Gift of gratitude",
    "Quest Gift of gratitude",
    "Quest Gift of gratitude",
    "Quest A song for god",
    "Quest A song for god",
    "Quest A song for god",
    "Quest Slay the machine",
    "Quest Slay the machine",
    "Quest Enchanted brush",
    "Quest Enchanted brush",
    "Quest Enchanted brush",
    "Quest Heretics' beasts",
    "Quest Heretics' beasts",
    "Quest Heretics' beasts",
    "Quest Grave of a bounty hunter",
    "Quest Grave of a bounty hunter",
    "Quest Grave of a bounty hunter",
    "Quest Inventive seamstress",
    "Quest Inventive seamstress",
    "Quest Puppeteer's lament",
    "Quest Puppeteer's lament",
    "Quest Puppeteer's lament",
    "Quest Revenge has teeth",
    "Quest Revenge has teeth",
    "Quest Night patrol",
    "Quest Night patrol",
    "Quest Night patrol",
    "Quest Trapped",
    "Quest Trapped",
    "Quest Trapped",
    "Quest Trapped",
    "Quest Mythical Badge",
    "Quest Mythical Badge",
    "Quest Mythical Badge",
    "Quest Secret machine",
    "Quest Secret machine",
    "Quest Soulful Horn",
    "Quest Soulful Horn",
    "Quest Soulful Horn",
    "Quest A dangerous cocktail",
    "Quest A dangerous cocktail",
    "Quest Source of inspiration",
    "Quest Source of inspiration",
    "Quest Youth potion",
    "Quest Youth potion",
    "Quest Youth potion",
    "Quest Beast summoner",
    "Quest Beast summoner",
    "Quest Beast summoner",
    "Quest What seekers seek",
    "Quest What seekers seek",
    "Quest What seekers seek",
    "Quest True colors",
    "Quest True colors",
    "Quest True colors",
    "Quest Ultimate craving",
    "Quest Ultimate craving",
    "Quest Ultimate craving",
    "Quest Ultimate craving",
    "Quest Spell for spell",
    "Quest Spell for spell",
    "Quest Spell for spell",
    "Quest Unfired firework",
    "Quest Unfired firework",
    "Quest Unfired firework",
    "Quest Time doesn't heal",
    "Quest Time doesn't heal",
    "Quest Time doesn't heal",
    "Quest A man for a chocobo girl",
    "Quest A man for a chocobo girl",
    "Quest A man for a chocobo girl",
    "Quest Rebuilding",
    "Quest Rebuilding",
    "Quest Sun flower",
    "Quest Sun flower",
    "Quest Moon flower",
    "Quest Moon flower",
    "Quest Moon flower",
    "Quest Secret of the Chocoborel",
    "Quest Secret of the Chocoborel",
    "Quest Secret of the Chocoborel",
    "Quest Wildlands in danger!",
    "Quest Wildlands in danger!",
    "Quest Wildlands in danger!",
    "Quest Hunting the hunter",
    "Quest Hunting the hunter",
    "Quest Hunting the hunter",
    "Quest Forget me not",
    "Quest Forget me not",
    "Quest Forget me not",
    "Quest A word of thanks",
    "Quest A word of thanks",
    "Quest A word of thanks",
    "Quest Fresh fertilizer",
    "Quest Fresh fertilizer",
    "Quest Fresh fertilizer",
    "Quest For the future",
    "Quest For the future",
    "Quest For the future",
    "Quest Dumpling cook-off",
    "Quest Dumpling cook-off",
    "Quest Dumpling cook-off",
    "Quest Brain over brawn",
    "Quest Brain over brawn",
    "Quest Brain over brawn",
    "Quest Hunter's challenge",
    "Quest Hunter's challenge",
    "Quest Hunter's challenge",
    "Quest A secret wish",
    "Quest A secret wish",
    "Quest A secret wish",
    "Quest Moghan's plea",
    "Quest Moghan's plea",
    "Quest Moghan's plea",
    "Quest What's in a brew?",
    "Quest What's in a brew?",
    "Quest What's in a brew?",
    "Quest What's in a brew?",
    "Quest A prayer to a goddess",
    "Quest A prayer to a goddess",
    "Quest A prayer to a goddess",
    "Quest Gatekeeper's curiosity",
    "Quest Gatekeeper's curiosity",
    "Quest Grave of a bounty hunter",
    "Quest Grave of a bounty hunter",
    "Quest Grave of a bounty hunter",
    "Quest A voice from below",
    "Quest A voice from below",
    "Quest A voice from below",
    "Quest Chocobo chow",
    "Quest Chocobo chow",
    "Quest Chocobo chow",
    "Quest Sylkis secrets",
    "Quest Sylkis secrets",
    "Quest Sylkis secrets",
    "Quest Digging mole",
    "Quest Digging mole",
    "Quest Digging mole",
    "Quest Two together",
    "Quest Two together",
    "Quest Two together",
    "Quest Emergency treatment",
    "Quest Emergency treatment",
    "Quest Emergency treatment",
    "Quest Moogle gourmand",
    "Quest Moogle gourmand",
    "Quest Moogle gourmand",
    "Quest Flower in the sands",
    "Quest Flower in the sands",
    "Quest Biologically speaking",
    "Quest Biologically speaking",
    "Quest The real client",
    "Quest The real client",
    "Quest The real client",
    "Quest For my child",
    "Quest For my child",
    "Quest For my child",
    "Quest Bandits' new weapon",
    "Quest Bandits' new weapon",
    "Quest Bandits' new weapon",
    "Quest Banned goods",
    "Quest Banned goods",
    "Quest Banned goods",
    "Quest Climbing the ranks I",
    "Quest Climbing the ranks I",
    "Quest Miracle vintage",
    "Quest Miracle vintage",
    "Quest Miracle vintage",
    "Quest Climbing the ranks II",
    "Quest Climbing the ranks II",
    "Quest Heightened security",
    "Quest Heightened security",
    "Quest Heightened security",
    "Quest Desert cleanup",
    "Quest Desert cleanup",
    "Quest Desert cleanup",
    "Quest A treasure for a god",
    "Quest A treasure for a god",
    "Quest Lucky Charm",
    "Quest Lucky Charm",
    "Quest Supply and demand",
    "Quest Supply and demand",
    "Quest Supply and demand",
    "Quest A new application",
    "Quest A new application",
    "Quest A new application",
    "Quest Pride and greed I",
    "Quest Pride and greed I",
    "Quest Pride and greed I",
    "Quest Pride and greed II",
    "Quest Pride and greed II",
    "Quest Pride and greed II",
    "Quest Pride and greed III",
    "Quest Pride and greed III",
    "Quest Pride and greed III",
    "Quest Key to her heart",
    "Quest Key to her heart",
    "Quest Key to her heart",
    "Quest Global: Roadworks I",
    "Quest Global: Roadworks I",
    "Quest Global: Roadworks I",
    "Quest Global: Roadworks II",
    "Quest Global: Roadworks II",
    "Quest Global: Roadworks II",
    "Quest Global: Roadworks III",
    "Quest Global: Roadworks III",
    "Quest Global: Roadworks III",
    "Quest Global: A girl's challenge",
    "Quest Global: A girl's challenge",
    "Quest Global: What's left behind",
    "Quest Global: What's left behind",
    "Quest Global: Seeing the dawn",
    "Quest Global: Seeing the dawn",
    "Quest Global: Staying sharp",
    "Quest Global: Staying sharp",
    "Quest Global: Where Moogles be",
    "Quest Global: Where Moogles be",
    "Quest Global: Fading prayer",
    "Quest Global: Fading prayer",
    "Quest Global: Forbidden tome",
    "Quest Global: Forbidden tome",
    "Quest Global: Shoot for the sky",
    "Quest Global: Shoot for the sky",
    "Quest Global: Shoot for the sky",
    "Quest Global: Digging mysteries",
    "Quest Global: Digging mysteries",
    "Quest Global: Digging mysteries",
    "20 Soul Seeds",
    "40 Soul Seeds",
    "60 Soul Seeds",
    "80 Soul Seeds",
    "100 Soul Seeds",
    "Replace EP Ability Curaga",
    "Replace EP Ability Teleport",
    "Replace EP Ability Escape",
    "Replace EP Ability Chronostasis",
    "Noel Drop",
    "Noel+ Drop",
    "Caius Drop",
    "Cyclops Omega Drop",
    "Reaver Omega Drop",
    "Skeleton Omega Drop"
];